title: Student Deals Blog
description: A blog for student discounts and tips
theme: jekyll-theme-cayman
title: Student Deals Blog
description: A blog for student discounts and tips
theme: jekyll-theme-minimal
author: Louis
show_downloads: false
